{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modelmetrics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ModelMetrics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ModelMetrics/ModelMetrics_{{ version }}.tar.gz
  sha256: 487d53fda57da4b29f83a927dda8b1ae6655ab044ee3eec33c38aeb27eed3d85

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ModelMetrics')"           # [not win]
    - "\"%R%\" -e \"library('ModelMetrics')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ModelMetrics
  license: GPL (>= 2)
  summary: Collection of metrics for evaluating models written in C++ using 'Rcpp'.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: ModelMetrics
# Title: Rapid Calculation of Model Metrics
# Version: 1.1.0
# Authors@R: person("Tyler", "Hunt", email = "thunt@snapfinance.com", role = c("aut", "cre"))
# Description: Collection of metrics for evaluating models written in C++ using 'Rcpp'.
# Depends: R (>= 3.2.2)
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# LinkingTo: Rcpp
# Imports: Rcpp
# RoxygenNote: 5.0.1
# Suggests: testthat
# NeedsCompilation: yes
# Packaged: 2016-08-26 15:27:50 UTC; snapadmin
# Author: Tyler Hunt [aut, cre]
# Maintainer: Tyler Hunt <thunt@snapfinance.com>
# Repository: CRAN
# Date/Publication: 2016-08-26 20:35:22

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
