travis:
  secure:
    BINSTAR_TOKEN: a4PB/aIQ/9VhIHhAbiUALqvNUwe1SDipKCcqT+f2jgRXnfbv8sPCicJndcBVzvAk+CflWHrnwrHM9J8xolVmLqkOpTM0KpbDbNF5IBDwDKZimnyWqmlJjcqrYubGtfi8Ej6fPmmsZt7PCyx1shuC3dQwc4/NLmEpznOwD+WPlaQnnywheadHDzFLw9Gx3DV+6prWqCheSKJ8XKclCmwoj98RgHeVVc21w6aGqpM8m/Wa8K1OOhNFut9I3iRsJlQwULLeOo6SB4IciHxKisSD8YoZallM19PX+j+E0T7O7O64v3IhiHyVyFSIRy0qQDnlxffoO5k155bB9bzg8JD69e7tMh4ix9lHNTxslWSSHZSh6YbpehKl5llCCro+MF/4FOUCB36QE8fdw6z0cB5xJT4SA5HQEtT7q02++UzukWlzg/1C4FlovQ9L+05lKBzgbF/I6xZfXeWEhPYYvRTwcFhlYqLfeKyHHuUSnD6eAbdB1kh+TSHh5G3NFoSG76GwtoRd0QTwbeUz0Y64V30oNRb1d9t8pJeMlPrnFk42Ww7DvsqMuCYPLuYxNro1ZQOraUYuDAHHyxhirXK7e7h8U9jhF3xsDCT2K50L10LzifM1WkkUV+FbO6G0SM3VD+D3X6U+fG0u83Bm6JASd+XyxvEYG9D/azHkE44EXJdHr4I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
