travis:
  secure:
    BINSTAR_TOKEN: ITUwmVI+30IzqQUQRTuce5zGQbZPz2xcRxWzxUtnSzhZSJP+3hsOxwkNooQa741RH9RaSj77ffej2bA08TyRi02KGxXXXvuQS4co7+JHylt1IQ2/PUiOinvzdwX60/G07i1TbUEcSHTO3QV1rBhYwG0sVhlevj+UJ6aAGbeu25ywdscTcr7XyNFUpx4AGYFXeEIg38nO3ljlIo2VgN2J+Yo9w3Ef7nB5+pVPY211NJDQOwtslo1H7yYvpVWuZp5kOvBcRBq0lpSRbMfYdmh6b32nHNyyFJPtoTBF7OWD28aIPTrGOas1DJP5PgqPG6xon0WJApO754qaiDgM0w/jf6oAB+1yvxOqt7mQWKWjKp69n0yKUeRC5TKkiDN01i8mGhuMyhrkjAzrrAvWXGi0Z/1ffHj6SnHREcX4H4IfXWCKZDkAfNF2e03AxUW4JKoI4zEBD41umd/DQVbL5ztjXAXZDtC2Em7oatb9o9F0yPE7r1Tf4Qopk0qUZLwq4x3EoZ9WnHD2558/zM6UUWg6RO5K+ce10HW3qoSgDkLzZN+CCI2ZxyeDLYCaBUM44wV6B3oLOkfWOm1T1IXljczL8BYkel7cO6KAIVZ6lKimjyt0UJ5sc6WWIo1j9WVlFSYO+vC3HeLzPZ7CGmz5nC2/d7MRGmGtteqcLQilskfpn3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
